spring:
  datasource:
    hikari: #real-db를 사용할 경우 override
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      data-username: sa

  h2:
    console:
      enabled: true
      path: /test-db

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true